//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "brc20_token")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub tick: String,
  pub inscription_id: String,
  pub inscription_number: i32,
  #[sea_orm(column_type = "Decimal(Some((20, 0)))", nullable)]
  pub supply: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 0)))", nullable)]
  pub minted: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 0)))", nullable)]
  pub limit_per_mint: Decimal,
  pub decimal: u8,
  pub deploy_by: String,
  pub deployed_number: u32,
  pub deployed_timestamp: u32,
  pub latest_mint_number: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
