//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "brc20_user_balance")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub address: Option<String>,
  pub sctipt_hash: Option<String>,
  pub tick: String,
  #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
  pub overall_balance: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
  pub transferable_balance: Decimal,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
