//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ord_rune_entries")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub burned: Decimal,
  pub deadline: Option<u32>,
  pub divisibility: u8,
  pub end: Option<u32>,
  pub etching: Vec<u8>,
  pub limit: Option<Decimal>,
  pub mints: u64,
  #[sea_orm(primary_key, auto_increment = false)]
  pub number: u64,
  pub rune: Decimal,
  pub spacers: u32,
  pub supply: Decimal,
  pub symbol: Option<String>,
  pub timestamp: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
