//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ord_inscription_entries")]
pub struct Model {
  pub charms: u16,
  pub fee: u64,
  pub height: u32,
  pub id: Vec<u8>,
  pub inscription_number: i32,
  pub parent: Option<u32>,
  pub sat: Option<u64>,
  #[sea_orm(primary_key, auto_increment = false)]
  pub sequence_number: u32,
  pub timestamp: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
