//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ord_transactions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub hash: Vec<u8>,
  #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
  pub raw_data: Vec<u8>,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
