//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::ord_inscription_entries::Entity as OrdInscriptionEntries;
pub use super::ord_rune_entries::Entity as OrdRuneEntries;
pub use super::ord_transactions::Entity as OrdTransactions;
pub use super::schema_migrations::Entity as SchemaMigrations;
